spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080